### ISSUE TITLE
Height status higher than blockchain height - Miner still loading

### ISSUE THREAD

**Issue by KevinWassermann94** [NebraLtd/hm-diag#80] opened 2021-07-14 10:53 UTC
![image](https://user-images.githubusercontent.com/82943687/125610035-899a93d3-1144-42df-af02-f06e626591ac.png)

Since a few releases I have noticed that the height status sometimes gets higher than the displayed blockchain height and shows as "Miner Is Still Loading" in the sync percentage. This has confused a few customers.

Can we still show a 100% sync status when the height status is higher than the reported blockchain height, at least if it is less than 20 blocks?

**Comment by vpetersson** [comment] 2021-07-14 10:54
Gotcha. Yeah @robputt is going to rework most of this code in the coming days.

**Comment by vpetersson** [comment] 2021-07-15 10:18
@KevinWassermann94 can you confirm that this is still an issue? We've made a few changes with regards to this in the last week.

**Comment by KevinWassermann94** [comment] 2021-07-15 10:53
The screenshot I made is from yesterday so it is probably still happening. It only happens sporadically though

**Comment by KevinWassermann94** [comment] 2021-07-15 11:26
@vpetersson Found it just now on a customer device. It is still an issue

**Comment by vpetersson** [comment] 2021-07-15 11:35
Noted. Ping @robputt.

**Comment by shawaj** [comment] 2021-07-15 16:56
@KevinWassermann94 is this just after a reboot or the device has been on for some time?

It might be an issue with the miner code itself

**Comment by KevinWassermann94** [comment] 2021-07-15 17:10
@shawaj This seems to happen on hotspots that are running for a longer time. I mostly see it randomly on customer devices and I have seen it rarely on my own hs

**Comment by shawaj** [comment] 2021-07-15 22:52
I wonder if it's just a caching issue of some sort. If you see it again could you try ctrl-F5 on the page and see if a refresh solves it?

**Comment by shawaj** [comment] 2021-07-16 05:53
![signal-2021-07-16-064930](https://user-images.githubusercontent.com/3359418/125898800-77c7ce4d-ae01-4092-8002-76da63e487cc.jpg)

Here's another example. I think the issue is that the Helium API is lagging behind. Because I went on explorer at the same time and it showed the same block but the miner itself showed higher

**Comment by shawaj** [comment] 2021-07-16 06:02
https://github.com/NebraLtd/hm-diag/master/diagnostics-program/html_generator.py#L91-L98

**Comment by vpetersson** [comment] 2021-07-16 07:56
There are ways we can work around this, but first we need the rewrite to complete.

**Comment by KevinWassermann94** [comment] 2021-07-17 00:01
Refreshing doesn't resolve it, but it is usually gone after the diagnostics page has updated after 2 minutes

**Comment by shawaj** [comment] 2021-07-17 13:22
I'm not sure why the API lags behind

**Comment by robputt** [comment] 2021-08-05 13:20
This disappears in #92 as the new page design does not have a "miner status" field, only a sync percentage. When block on the miner is > than block on the API it now shows 100%.

**Comment by shawaj** [comment] 2021-08-16 16:42
Closing this in favour of #104 because this issue no longer occurs and now it goes to over 100%

**Closed by shawaj** 2021-08-16 16:42 UTC
Labels: bug
