### ISSUE TITLE
AT&T 3G switch off - EG25-G firmware update

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-diag#133] opened 2021-08-26 15:13 UTC
AT&T are switching off 3G in USA in February 2022 which means we need to apply a firmware update to any EG25G mPCIe modules for them to continue working on AT&T.

This can be done with AT commands or via a full firmware update. Full firmware update is preferable.

Need to work out the best way to roll this out.

- [Quectel_EC2x&EG9x&EG2x-G_Series_Software_Configuration_for_AT&T_3G_Sunset_Guide_V1.0.pdf](https://github.com/NebraLtd/hm-diag/files/7060740/Quectel_EC2x.EG9x.EG2x-G_Series_Software_Configuration_for_AT.T_3G_Sunset_Guide_V1.0.pdf)
- [AT&T 3G switch off document.docx](https://github.com/NebraLtd/hm-diag/files/7060741/AT.T.3G.switch.off.document.docx)
- [ATT 3G Sunset affected FW.pdf](https://github.com/NebraLtd/hm-diag/files/7060742/ATT.3G.Sunset.affected.FW.pdf)
- [Quectel_EOL 2021081201_EC25-EUX&EC21-EUX(Mini PCIe)_Module_EOL_Notification.pdf](https://github.com/NebraLtd/hm-diag/files/7060743/Quectel_EOL.2021081201_EC25-EUX.EC21-EUX.Mini.PCIe._Module_EOL_Notification.pdf)

- Check model and figure out if EG25-G is what we care about.
- Check firmware version.
- Include firmware update payload in container so its already there when needed.
- Figure out a method to updrade firmware
- Consider rollback logic after Xmin where connection hasn't established.

**Comment by shawaj** [comment] 2021-12-28 15:44
Just a ping on this @marvinmarnold @vpetersson as needs sorting by Feb

**Comment by vpetersson** [comment] 2022-01-04 12:15
@shawaj Do we have any of these boards so that we can test it?

**Comment by shawaj** [comment] 2022-01-06 17:11
yes we have thousands - it is just our standard mPCIe 4g module (think you have one in your outdoor miner?)

**Comment by pritamghanghas** [comment] 2022-02-07 14:26
### Plan to implement it:
# compiling QFireHose flashing tool into hm-diag docker image
* compile and install QFirehose as /usr/sbin/QFirehose. hm-diag repository carries the tool source and firmware in the following structure.

> quectel/
> ├── firmware
> │   └── eg25-g
> │       └── EG25GGBR07A08M2G_30.006.30.006
> │           ├── contents.xml
> │           ├── md5.txt
> │           └── update
> │               ├── appsboot.mbn
> │               ├── ENPRG9x07.mbn
> │               ├── firehose
> │               │   ├── partition_complete_p2K_b128K.mbn
> │               │   ├── patch_p2K_b128K.xml
> │               │   ├── prog_nand_firehose_9x07.mbn
> │               │   └── rawprogram_nand_p2K_b128K_update.xml
> │               ├── mdm9607-boot.img
> │               ├── mdm9607-recovery.ubi
> │               ├── mdm9607-sysfs.ubi
> │               ├── NON-HLOS.ubi
> │               ├── NPRG9x07.mbn
> │               ├── partition.mbn
> │               ├── partition_nand.xml
> │               ├── rpm.mbn
> │               ├── sbl1.mbn
> │               ├── tz.mbn
> │               └── usrdata.ubi
> └── qfirehose
>     └── QFirehose_Linux_Android_V1.4.9.tar

# firmware upgrade stub will go in hm-diag initialization before Flask app starts executing. ensure_healthy_modem() function will use two proxy classes for working with systemd and modemmanager over dbus.

-  systemd dbus interface for starting and stopping modem manager unit
-  modemmanager dbus interface for sending and receiving AT commands.

I was using https://github.com/vtsingaras/python-systemctl for the systemd interface. As discussed in sprint, I don't need the full interface. I can write a small class of my own to wrap the dbus calls.
For ModemManager there was no ready made python lib that abstracts out dbus, I have written my own class.

**Comment by pritamghanghas** [comment] 2022-02-08 07:31
After yesterday's discussion, I looked at various python dbus projects. In my view only dasbus makes sense among current options. It has good api as far as i looked. I think it is able to generated complete object api without a codegen or manually writing code, probably becuase of python3-gi.

**Comment by pritamghanghas** [comment] 2022-02-14 14:00
gunicorns kills the wsgi server. This happens because ensure_quectel_health() can run for as much as 3 minutes depending on how many things it is doing. 

[2022-02-14 06:15:38 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:8)
[2022-02-14 06:15:39 +0000] [1] [WARNING] Worker with pid 8 was terminated due to signal 9

**Comment by pritamghanghas** [comment] 2022-02-17 17:47
@marvinmarnold

Can we try calling AT&T if they have some special configuration for Linux IoT devices? 
I have tried following apn fields: NXTGENPHONE, Broadband, Phone. Basically from this page https://www.att.com/support/article/wireless/KM1062162/

None of them has worked yet. Mostly all of them fail at last stage of connection establishment. Keeps repeating this. It is not effecting the upgrade but want to test once that connectivity is not lost after an upgrade. 
Sample log from modem manager. 
```
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0/bearer348] connection attempt #1 failed: QMI protocol error (14): 'CallFailed'
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0] state changed (connecting -> enabled)
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0/bearer348] connection #1 finished: duration 0s, tx: 0 bytes, rx :0 bytes
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0] simple connect started...
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0] simple connect state (4/8): wait to get fully enabled
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0] simple connect state (5/8): register
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0] simple connect state (6/8): bearer
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0] simple connect state (7/8): connect
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0] state changed (enabled -> connecting)
Feb 17 17:30:06 2452bfb ModemManager[6710]: [modem0/bearer349] couldn't start network: QMI protocol error (14): 'CallFailed'
```

**Comment by marvinmarnold** [comment] 2022-02-17 17:55
@pritamghanghas can you try these? https://support.marketplace.iot.attcompute.com/help/what-apn-or-how-can-i-find-the-apn-that-i-need-to-use-for-my-device

**Comment by pritamghanghas** [comment] 2022-02-17 18:10
@marvinmarnold hasn't worked with these APNs. Somethings are different about their configuration page. 

They don't mention the number which is generally *99$. I have tried with and without it.  But still no luck.

**Comment by marvinmarnold** [comment] 2022-02-17 18:44
@pritamghanghas looks like I messed up and this SIM is restricted for approved devices. I'm trying to connect with T-Mobile to see if they can get me something ASAP.

![image](https://user-images.githubusercontent.com/1311030/154549253-f0eee89b-678b-4be8-af94-e1cedaffa4e5.png)

**Comment by pritamghanghas** [comment] 2022-02-18 11:29
@marvinmarnold I was able to test the flow on Kevin's miner. It didn't have any problem with the update. But it has EG25GGBR07A08M2G revision.

The one on your desk is EG25GGBR07A08M2G. 
On this miner t-mobile sim worked but only gave ipv6 address. This happens with firmware version EG25GGBR07A07M2G_30.003.30.003. With older firmware this gets ipv4 as well. Not sure if that creates any problem on our stack.  See verfication logs below.

```
root@2452bfb:~# journalctl -f -u ModemManager
-- Logs begin at Fri 2022-02-18 08:57:23 UTC. --
Feb 18 08:58:09 2452bfb ModemManager[1391]: [/dev/cdc-wdm0] Allocating new client ID...
Feb 18 08:58:09 2452bfb ModemManager[1391]: [/dev/cdc-wdm0] Registered 'wds' (version 1.67) client with ID '18'
Feb 18 08:58:09 2452bfb ModemManager[1391]: [modem0/bearer0] QMI IPv6 Settings:
Feb 18 08:58:09 2452bfb ModemManager[1391]: [modem0/bearer0]     address: 2607:fb90:534f:14cc:83b:f8fa:d82b:7213/64
Feb 18 08:58:09 2452bfb ModemManager[1391]: [modem0/bearer0]     gateway: 2607:fb90:534f:14cc:c16c:ba8e:e26c:f1ca/64
Feb 18 08:58:09 2452bfb ModemManager[1391]: [modem0/bearer0]     DNS #1: fd00:976a::9
Feb 18 08:58:09 2452bfb ModemManager[1391]: [modem0/bearer0]     DNS #2: fd00:976a::10
Feb 18 08:58:09 2452bfb ModemManager[1391]: [modem0/bearer0]        MTU: 1500
Feb 18 08:58:09 2452bfb ModemManager[1391]: [modem0] state changed (registered -> connected)
Feb 18 08:58:09 2452bfb ModemManager[1391]: [modem0] simple connect state (8/8): all done
```

```
wwan0     Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  
          inet6 addr: 2607:fb90:534f:14cc:83b:f8fa:d82b:7213/64 Scope:Global
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:130 errors:0 dropped:0 overruns:0 frame:0
          TX packets:151 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:65053 (63.5 KiB)  TX bytes:31948 (31.1 KiB)
```

```
root@2452bfb:~# ping6 -I wwan0 gogle.com
PING gogle.com (2607:f8b0:4023:1002::6a): 56 data bytes
64 bytes from 2607:f8b0:4023:1002::6a: seq=0 ttl=100 time=124.351 ms
64 bytes from 2607:f8b0:4023:1002::6a: seq=1 ttl=100 time=84.976 ms
```

All in all both upgrades didn't have an impact on the connectivity on both hw revisions. Two vendor tested 'T-Mobile' and 'Smarty'

**Comment by marvinmarnold** [comment] 2022-02-25 20:29
@pritamghanghas what is left for us to close this?

**Comment by marvinmarnold** [comment] 2022-02-28 13:55
Todo:

- Some test cases
- MD5 -> SHA256
- Test ipv6 with Marvin's tmobile SIM
- Following test, enable feature flag on 868-outdoor

**Comment by pritamghanghas** [comment] 2022-03-02 13:15
Balena dashboard and cli seems to be working with ipv6. Yesterday it was a little slow but it was working fine today. 

But our apps eg diagnostics don't seem be getting internet connection while on ipv6. Both urllib and requests failed to do a head request. 

requests spits out this message. Seems like a routing issue: 
`WARNING:root:HTTPSConnectionPool(host='google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xf67653a0>: Failed to establish a new connection: [Errno 101] Network is unreachable')), retrying in 1 seconds...`

**Comment by pritamghanghas** [comment] 2022-03-02 13:26
This route works well on host. I think the routing problem is limited to docker networking.

**Comment by pritamghanghas** [comment] 2022-03-03 12:39
the ipv6 issue will be tracked separately [here](https://github.com/NebraLtd/hm-diag/issues/310)

**Closed** 2022-03-15 06:20 UTC
Labels: next sprint, needs triage
